name: kids_calendar
description: "亲子时光 - 一款面向家庭的亲子日程管理应用"
publish_to: 'none'
version: 0.5.0+5

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.0
  path: ^1.8.0
  path_provider: ^2.1.0
  intl: ^0.19.0
  provider: ^6.1.0
  flutter_local_notifications: ^17.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
